cache:
  enabled: false

debugger:
  enabled: true
  twig: true
  shutdown:
    close_connection: true

errors:
  display: true
  log: true

flex:
  cache:
    index:
      enabled: false
    object:
      enabled: false
    render:
      enabled: false

# let's use 3 character passwords on dev
pwd_regex: '^[ -~]{3,}$'